apiVersion: v1
kind: Service
metadata:
  name: deployment-lb-service
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }} # 30007 # assume this will change